// Made by scripts/generate_backing_sounds.py - do not edit by hand.
// Single piano notes by MIDI note number (60 = middle C), for ear training.

export const PIANO_NOTES: Record<number, number> = {
  48: require('../../assets/sounds/piano/c3.wav'),
  49: require('../../assets/sounds/piano/cs3.wav'),
  50: require('../../assets/sounds/piano/d3.wav'),
  51: require('../../assets/sounds/piano/ds3.wav'),
  52: require('../../assets/sounds/piano/e3.wav'),
  53: require('../../assets/sounds/piano/f3.wav'),
  54: require('../../assets/sounds/piano/fs3.wav'),
  55: require('../../assets/sounds/piano/g3.wav'),
  56: require('../../assets/sounds/piano/gs3.wav'),
  57: require('../../assets/sounds/piano/a3.wav'),
  58: require('../../assets/sounds/piano/as3.wav'),
  59: require('../../assets/sounds/piano/b3.wav'),
  60: require('../../assets/sounds/piano/c4.wav'),
  61: require('../../assets/sounds/piano/cs4.wav'),
  62: require('../../assets/sounds/piano/d4.wav'),
  63: require('../../assets/sounds/piano/ds4.wav'),
  64: require('../../assets/sounds/piano/e4.wav'),
  65: require('../../assets/sounds/piano/f4.wav'),
  66: require('../../assets/sounds/piano/fs4.wav'),
  67: require('../../assets/sounds/piano/g4.wav'),
  68: require('../../assets/sounds/piano/gs4.wav'),
  69: require('../../assets/sounds/piano/a4.wav'),
  70: require('../../assets/sounds/piano/as4.wav'),
  71: require('../../assets/sounds/piano/b4.wav'),
  72: require('../../assets/sounds/piano/c5.wav'),
  73: require('../../assets/sounds/piano/cs5.wav'),
  74: require('../../assets/sounds/piano/d5.wav'),
  75: require('../../assets/sounds/piano/ds5.wav'),
  76: require('../../assets/sounds/piano/e5.wav'),
  77: require('../../assets/sounds/piano/f5.wav'),
  78: require('../../assets/sounds/piano/fs5.wav'),
  79: require('../../assets/sounds/piano/g5.wav'),
  80: require('../../assets/sounds/piano/gs5.wav'),
  81: require('../../assets/sounds/piano/a5.wav'),
  82: require('../../assets/sounds/piano/as5.wav'),
  83: require('../../assets/sounds/piano/b5.wav'),
  84: require('../../assets/sounds/piano/c6.wav'),
};
